/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.felipeborges.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guest01
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmFuncionario = new javax.swing.JMenuItem();
        jmPessoa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmListarFuncionario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jbFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        jmFuncionario.setText("Funcionario");
        jmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmFuncionario);

        jmPessoa.setText("Pessoa");
        jMenu1.add(jmPessoa);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Listar");

        jmListarFuncionario.setText("Listar Funcionario");
        jmListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmListarFuncionario);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Alterar");

        jbFuncionario.setText("Funcionario");
        jbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(jbFuncionario);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFuncionarioActionPerformed
        TelaCadastroFuncionario tf = new TelaCadastroFuncionario(null);
        tf.setLocationRelativeTo(null);
        tf.setVisible(true);

    }//GEN-LAST:event_jmFuncionarioActionPerformed

    private void jmListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarFuncionarioActionPerformed
        TelaRelatoriosFuncionario tr = new TelaRelatoriosFuncionario();
        tr.setVisible(true);
    }//GEN-LAST:event_jmListarFuncionarioActionPerformed

    private void jbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFuncionarioActionPerformed
        TelaEditarFuncionario t = new TelaEditarFuncionario(null, 0, 0);
        t.setVisible(true);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbFuncionarioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jbFuncionario;
    private javax.swing.JMenuItem jmFuncionario;
    private javax.swing.JMenuItem jmListarFuncionario;
    private javax.swing.JMenuItem jmPessoa;
    // End of variables declaration//GEN-END:variables
}
